version: '3.6'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "7632"
    tty: true
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app:z
    networks:
      - ftcbot_dev
    
  broker:
    image: rabbitmq:3.7-alpine
    expose:
      - "4369"
      - "5671"
      - "25672"
    ports:
      - "5672:5672"
    networks:
      ftcbot_dev:
      
  websocket-cache:
    image: redis:alpine
    expose:
      - "6379"
    networks:
      ftcbot_dev:
      
networks:
  ftcbot_dev:
    external: true
 
