version: '3.6'
services:

  client:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "7632"
    tty: true
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app:z
    links: 
      - broker
      - cache
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      ftcbot:
    
  broker:
    image: rabbitmq:3.7-alpine
    expose:
      - "4369"
      - "5671"
      - "5672"
      - "25672"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      ftcbot:
      
  cache:
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - ./redis-data:/data:z
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      ftcbot:
      
networks:
    ftcbot:
        driver: bridge
 
 