version: '3'
services:

  client:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "7632"
    tty: true
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app:z
    links: 
      - broker
      - cache
    command: sh
    networks:
      default:
    
  broker:
    image: rabbitmq:3.7-alpine
    expose:
      - "4369"
      - "5671"
      - "5672"
      - "25672"
    networks:
      default:
      
  cache:
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - ./redis-data:/data:z
    networks:
      default:
      
networks:
    default:
        driver: bridge
 
 